2020-12-02 07:49:02,920 INFO    MainThread:16940 [wandb_init.py:_log_setup():292] Logging user logs to wandb/run-20201202_074902-p99xt4aa/logs/debug.log
2020-12-02 07:49:02,920 INFO    MainThread:16940 [wandb_init.py:_log_setup():293] Logging internal logs to wandb/run-20201202_074902-p99xt4aa/logs/debug-internal.log
2020-12-02 07:49:02,920 INFO    MainThread:16940 [wandb_setup.py:_flush():68] setting env: {}
2020-12-02 07:49:02,920 INFO    MainThread:16940 [wandb_setup.py:_flush():68] setting user settings: {}
2020-12-02 07:49:02,920 INFO    MainThread:16940 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-12-02 07:49:03,583 INFO    MainThread:16940 [wandb_run.py:_console_start():1265] atexit reg
2020-12-02 07:49:03,583 INFO    MainThread:16940 [wandb_run.py:_redirect():1135] redirect: SettingsConsole.REDIRECT
2020-12-02 07:49:03,583 INFO    MainThread:16940 [wandb_run.py:_redirect():1138] Redirecting console.
2020-12-02 07:49:03,584 INFO    MainThread:16940 [redirect.py:install():196] install start
2020-12-02 07:49:03,584 INFO    MainThread:16940 [redirect.py:install():211] install stop
2020-12-02 07:49:03,584 INFO    MainThread:16940 [redirect.py:install():196] install start
2020-12-02 07:49:03,585 INFO    MainThread:16940 [redirect.py:install():211] install stop
2020-12-02 07:49:03,585 INFO    MainThread:16940 [wandb_run.py:_redirect():1182] Redirects installed.
2020-12-02 08:04:06,354 ERROR   stderr    :16940 [redirect.py:_pipe_relay():129] problem in pipe relay
Traceback (most recent call last):
  File "/home/yz87/anaconda3/envs/torchpy3_7/lib/python3.7/site-packages/wandb/lib/redirect.py", line 127, in _pipe_relay
    cb(name, data)
  File "/home/yz87/anaconda3/envs/torchpy3_7/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 634, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/home/yz87/anaconda3/envs/torchpy3_7/lib/python3.7/site-packages/wandb/interface/interface.py", line 146, in publish_output
    self._publish_output(o)
  File "/home/yz87/anaconda3/envs/torchpy3_7/lib/python3.7/site-packages/wandb/interface/interface.py", line 151, in _publish_output
    self._publish(rec)
  File "/home/yz87/anaconda3/envs/torchpy3_7/lib/python3.7/site-packages/wandb/interface/interface.py", line 429, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2020-12-02 08:04:06,355 INFO    MainThread:16940 [wandb_run.py:_atexit_cleanup():1238] got exitcode: 255
2020-12-02 08:04:06,355 INFO    MainThread:16940 [wandb_run.py:_restore():1210] restore
2020-12-02 08:04:06,355 INFO    MainThread:16940 [redirect.py:uninstall():215] uninstall start
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():264] _stop: stdout
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():270] _stop closed: stdout
2020-12-02 08:04:06,356 INFO    stdout    :16940 [redirect.py:_pipe_relay():119] relay done saw last write: stdout
2020-12-02 08:04:06,356 INFO    stdout    :16940 [redirect.py:_pipe_relay():135] relay done done: stdout
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():276] _stop joined: stdout
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():278] _stop rd closed: stdout
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:uninstall():219] uninstall done
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:uninstall():215] uninstall start
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():264] _stop: stderr
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():270] _stop closed: stderr
2020-12-02 08:04:06,356 INFO    stderr    :16940 [redirect.py:_pipe_relay():119] relay done saw last write: stderr
2020-12-02 08:04:06,356 INFO    stderr    :16940 [redirect.py:_pipe_relay():135] relay done done: stderr
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():276] _stop joined: stderr
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:_stop():278] _stop rd closed: stderr
2020-12-02 08:04:06,356 INFO    MainThread:16940 [redirect.py:uninstall():219] uninstall done
2020-12-02 08:04:06,357 INFO    MainThread:16940 [wandb_run.py:_restore():1210] restore
2020-12-02 08:04:06,527 INFO    MainThread:16940 [internal.py:handle_exit():137] Internal process exited
